// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/blog/[slug]": InferRoute<import("./src/app/blog/[slug]/route-type").RouteType>;
  }

  interface StaticRouter {
    "/about": StaticRoute;
    "/": StaticRoute;
  }

  interface ExternalRouter {
    "/admin/index.html": StaticRoute;
    "/external-blog/[slug]": InferRoute<import("./src/external-routes/externalBlog").RouteType>;
  }
}
